### ISSUE TITLE
DMG file on sourceforge doesn't mount

### ISSUE THREAD

**Issue by glennreid** [timcharper/git_osx_installer#103]
https://sourceforge.net/projects/git-osx-installer/?source=typ_redirect has a .dmg download that seems to be broken.  I tried it twice and it says it doesn't contain a disk image.  Not sure where to get git 2 (I'm stuck with 1.7.7 in the meantime)

**Comment by orbsmiv** [comment]
Probably related to #101

**Comment by timcharper** [comment]
2.15.1 is released with HFS+ fs.
