### ISSUE TITLE
Cannot find git after git installation on Mac OSX Sierra 10.12.6

### ISSUE THREAD

**Issue by UPU710** [timcharper/git_osx_installer#110]
I had git already installed. Upon "which git" on Terminal I get: /usr/local/bin/git
In the Finder I find it however here: /Library/Developer/CommandLineTools/usr/bin/git
What is the difference between these two?

https://github.com/timcharper/git_osx_installer/blob/master/README.md suggests: 
sudo mv /usr/bin/git /usr/bin/git-system
sudo ln -sf /usr/local/git/bin/git /usr/bin/git

When I do so, it asks for my password and upon inserting it, the Terminal says: mv: rename /usr/bin/git to /usr/bin/git-system: Operation not permitted

How can I access the git? I need git to access it from RStudio. Rstudio/Tools/Global Options/Git/SVN.

**Comment by UPU710** [comment]
problem is solved.

**Comment by nikimich** [comment]
> How can I access the git? I need git to access it from RStudio. Rstudio/Tools/Global Options/Git/SVN.

What did you do?
