### ISSUE TITLE
Can't install on Yosemite 10.10.1

### ISSUE THREAD

**Issue by tomaslrcode** [timcharper/git_osx_installer#30]
I tried to install the latest version of GIT on my mac running 10.10.1 and as soon as i try to install it installer does not respond. I noticed on the version list it says only 10.10 for Yosemite so i was wondering if there was a fix in the near future for 10.10.1 users.

**Comment by timcharper** [comment]
Do you have the iOS emulator running, or anything Xcode related?

**Comment by lesteratsciencebite** [comment]
I ran the installer for version git version 2.2.1 today on Yosemite 10.10.1 today.  It seemed to have worked, however, if I use git --version, it still says I'm on 1.9.3.   Does this require a restart of the system?

**Comment by tomaslrcode** [comment]
Yes I have Xcode in my computer as well as some other compiles which I use.

**Comment by tomaslrcode** [comment]
I tried it again this morning and it worked 2.2.1 on 10.10.1. Thanks for your time it probablby was an issue with my computer and not git.
