### ISSUE TITLE
After uninstall git, PATH variable still contain '/usr/local/git/bin'.

### ISSUE THREAD

**Issue by zzp0** [timcharper/git_osx_installer#32]
In my ~/.bash_profile,  PATH variable is `export PATH=/usr/local/sbin:$PATH`.  `echo $PATH` return `/usr/local/sbin:/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin                                                                 `

**Comment by timcharper** [comment]
Look for `/etc/paths.d/git`; does that file still exist?

**Comment by zzp0** [comment]
Thanks reply. 
`/etc/paths.d/git`  does not exist.

**Comment by timcharper** [comment]
Then it must be set via another mechanism, or you need to restart your shell?

**Comment by FrogyYen** [comment]
restart the shell is important!  thanks a lot!!
