### ISSUE TITLE
New Mac user

### ISSUE THREAD

**Issue by gbr0wn** [timcharper/git_osx_installer#34]
I got fed up with viruses, shakedown artists "protecting" me from viruses, bought a Mac.  I can't open a command line, don't know how to figure out what the operating system is, downloaded github, get an icon of some device in upper right of my screen which I open, it goes through and installation, says "complete"  but nothing in "Launcher" or on my list of executable files to launch the program

**Comment by timcharper** [comment]
Git is a command line tool. I'm sorry, but I barely have enough support time to provide for those who have genuine issues with the installer, let alone people who are new to Mac. 

If you need something, and are not comfortable with the commandline, look into source tree.

**Comment by timcharper** [comment]
http://www.sourcetreeapp.com
