### ISSUE TITLE
can't get the git working after updatng

### ISSUE THREAD

**Issue by premkgowda** [timcharper/git_osx_installer#37]
I have OSX 10.10.1 and ran the following command

sudo mv /usr/bin/git /usr/bin/git-xcode
sudo ln -sf /usr/local/git/bin/git /usr/bin/git

after I run the command,  I can't git --version working and if I run any git command I get the following error.
I am new to programming and git . Please help
/usr/bin/git: No such file or directory

**Comment by timcharper** [comment]
bash caches command location resolution; Just restart all of your bash sessions to resolve.

**Comment by timcharper** [comment]
Updated README to help future travelers. https://github.com/timcharper/git_osx_installer/commit/a40d7121a845d2efdad34da9ca1515cb523332e3
