### ISSUE TITLE
PackageMaker is no longer part of OS X

### ISSUE THREAD

**Issue by paulschreiber** [timcharper/git_osx_installer#38]
PackageMaker is no longer part of OS X, and git_osx_installer requires it. When you try and build the installer on 10.10.2, you see this:

```
$ make
Unable to find any of /Developer/Applications/Utilities/PackageMaker.app /Applications/Utilities/PackageMaker.app
# OSX_NAME = Snow Leopard
# OSX_CODE = snow-leopard
# ARCH = Universal
# ARCH_CODE = universal
# CFLAGS = -mmacosx-version-min=10.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform -DMACOSX_DEPLOYMENT_TARGET=10.6 -arch x86_64 -arch i386
# BUILD_CODE = intel-universal-snow-leopard
```

**Comment by timcharper** [comment]
It hasn't been a part of OS X for a while; perhaps a README mention would help;

Download Auxiliary Tools for Xcode. https://developer.apple.com/downloads/index.action?name=PackageMaker

**Comment by paulschreiber** [comment]
The most recent version of PackageMaker is from 2012, and probably isn't compatible with Yosemite.

It'd be good to use pkgbuild, productbuild, and pkgutil instead.

http://stackoverflow.com/questions/11487596/making-os-x-installer-packages-like-a-pro-xcode4-developer-id-mountain-lion-re

**Comment by timcharper** [comment]
It is compatible. I use it.

**Comment by MrJoy** [comment]
The Auxiliary Tools, as of "Auxiliary Tools for Xcode 7", no longer includes PackageMaker.

**Comment by timcharper** [comment]
It's been switched! PackageMaker is gone! Using pkgbuild now. https://github.com/timcharper/git_osx_installer/blob/a07ddae/Makefile#L172

**Comment by MrJoy** [comment]
:+1:
