### ISSUE TITLE
Does not install in macbook pro

### ISSUE THREAD

**Issue by ShakunK** [timcharper/git_osx_installer#40]

**Comment by timcharper** [comment]
I suppose there have been less helpful bug reports, but I'm struggling to remember any at this time.

**Comment by ShakunK** [comment]
does not pass through my mcafee (macbook pro). I tried to download it manually, but I cannot find where it is, it is not in application.

**Comment by timcharper** [comment]
I have no idea how to fix your problem. Sorry.
