### ISSUE TITLE
Version out of date?

### ISSUE THREAD

**Issue by garysweaver** [timcharper/git_osx_installer#41]
Thanks for all of your work! I've been using the OS X installer for Git for a while now since I had a problem with homebrew's version not being up-to-date some time ago. Unfortunately, as of 2015-03-11 things are the other way around. Git OS X Installer in Sourceforge [downloads](http://sourceforge.net/projects/git-osx-installer/) page has 2.2.1 as latest OS X version, but [git-scm](http://git-scm.com/) site has 2.3.2 as latest and current homebrew [git](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/git.rb) also showing 2.3.2.

Maybe would be good to contact the folks at [git-scm.com](https://github.com/git/git-scm.com) to help keep an eye out to make sure [downloads](http://sourceforge.net/projects/git-osx-installer/) is up-to-date?

Thanks for your help!

**Comment by paulschreiber** [comment]
The latest git release is 2.3.4; the latest installer release is 2.2.1. Please release an updated installer.

**Comment by garysweaver** [comment]
Since the OS X installer provided by this project (and git-scm.com) is no longer up-to-date and the homebrew version is, here is how to uninstall the git installed by this installer:

    sudo rm -rf /usr/local/git/ /usr/bin/git /etc/paths.d/git /etc/manpaths.d/git

Then install [homebrew|http://brew.sh/], if you haven't, and:

    brew update
    brew install git

Then fix any paths/etc. that might be dependent on the other git, if any, and restart Terminal.app.

To upgrade whenever homebrew updates git (and it seems to stay up-to-date recently), do:

    brew upgrade git

**Comment by timcharper** [comment]
2.3.5 deployed

**Comment by garysweaver** [comment]
Thanks!
