### ISSUE TITLE
Trying to install Git on Mac w/ OS Lion 10.7.5

### ISSUE THREAD

**Issue by Cinnym0n** [timcharper/git_osx_installer#42]
I downloaded Git 2.2.1 which reported that it installed successfully.
I tried "git --version" in the terminal window and got "segmentation fault: 11"
(Same error with any Git command)
I found references (stackoverflow) that said Git 2.2.1 will not run on Mac w/ Lion 10.7.5 and that I should use version 1.8.4.2 - so I tried to uninstall it.
 
I clicked the uninstall icon in the Git window. It wanted to load Xcode component "Mobile Device Franmework" so I tried to let it, but I got "an unknown error occurred see install log" -> nothing there
Looked at "All Messages" window and got:
authorizationhost:SFBuiltinEntitled: Xcode.app is not entitled for system.install.apple-software
(same repeated)
(same except end is apple-store-software)
(same as last line)
com.apple.SecurityServer: failed to authorize right 'system.install.app-srore-software' by client 'System/Library/PrivateFramwor

I have since tried to install Git 2.2.1 again several times (without uninstalling it), including from a page that had a comment from a user that said it worked for them using this OS when previous versions had failed and glad they no longer had to use older version, but I still get the same error (maybe because it won't overwrite what I already have with out me uninstalling it?)
[http://sourceforge.net/projects/git-osx-installer/?source=typ_redirect]

I also wanted to try to download the older version of Git (1.8.4.2), but couldn't figure out how to get the install package from the archive. 
Found a downloadable version, but i got a window saying the "file is deprecated"
[https://code.google.com/p/git-osx-installer/downloads/detail?name=git-1.8.4.2-intel-universal-snow-leopard.dmg&can=2&q=] 

Any insight would be appreciated.

**Comment by Cinnym0n** [comment]
Solved problem by installing a new version of the operating system.
Upgraded to OS X Yosemite and subsequently installed git 1.9.5 (Apple Git-50.3)

**Comment by timcharper** [comment]
Please see the readme.

**Comment by silviotroia** [comment]
+1

**Comment by davidmaxwaterman** [comment]
For convenience of anyone coming here wondering why it segfaults, the README is here:

https://github.com/timcharper/git_osx_installer/blob/master/README.md#which-version-should-i-download

"10.7 Lion: git-*-snow-leopard"

Not that that helps much.  Where is this 'git-*-show-leopard' file?

I look here, but no 'snow' anything:

https://mirrors.edge.kernel.org/pub/software/scm/git/

I have a feeling this should be more straight forward, but I suppose it could be just me being slow.

**Comment by Cinnym0n** [comment]
Sorry to say, it never worked. I had to upgrade my operating system
Cinnym0n
