### ISSUE TITLE
"Lazy symbol" error on Mac OS 10.8

### ISSUE THREAD

**Issue by jiffyclub** [timcharper/git_osx_installer#43]
Thanks for making these installers, they are a life saver on older versions of Mac OS X! I don't know if there's anything you can do, but I wanted to point you at a discussion concerning using the installers on OS 10.8: swcarpentry/workshop-template#196.

The summary is that when users are installing the snow-leopard version they are getting a "Lazy symbol" error that can only be fixed by installing XCode. One person has reported that the Git 1.8 installers work more reliably than the installers for more recent versions of Git. It hasn't been reported which version of Git was installed when users saw the "Lazy symbol" error.

**Comment by timcharper** [comment]
I have installed these on machines without Xcode installed and it works; admittedly, it may be that I have another bit of software installed on the machine as well which is causing it to work.

Do you have any idea how to resolve? I am specifying every make option conceivable to get it to link only to system libraries, that this still happens is pretty frustrating. The whole goal of this installer is to not require Xcode.

**Comment by jiffyclub** [comment]
We had a [new report](https://github.com/swcarpentry/workshop-template/issues/196#issuecomment-91621228) last week of the installers working great on a 10.8 machine without Xcode, so experience seems to be pretty varied. In general we fix this by installing either Xcode or the command line tools, but I'm not sure whether that fixes the installation of git-osx-installer or whether we end up using the git that comes with Xcode. (I think that it fixes git-osx-installer, but I could be wrong.)

**Comment by timcharper** [comment]
I just tested this on a 10.9 machine without Xcode; the stubs were an issue, but the software installed and ran fine without installing Xcode at all.

**Comment by jiffyclub** [comment]
I'll close this since I mostly wanted to make you aware of what we've been running into with Software Carpentry, and now you're aware! If we get any more reports or improved information I'll let you know. Thanks again for your work on this!
