### ISSUE TITLE
Mac download doesn't work

### ISSUE THREAD

**Issue by AceAttorneyMaster111** [timcharper/git_osx_installer#57]
I have downloaded the Mac OSX installer so many times. I open the dmg, go through the installer, and I can't find Git **ANYWHERE**! :rage: I use OS X Yosemite 10.10.5 on a MacBook Pro with Retina Display/

**Comment by timcharper** [comment]
Check /usr/local/git/bin/git

It adds entries to /etc/paths.d, but it does not remove the git stubs unfortunately that Apple started to ship.

**Comment by OldBunny2800** [comment]
Sorry, I can't find it. Where do I go? Here is what I can see: ![Finder](http://i.imgur.com/yp2UOA5.png) How do I get to /usr?

**Comment by timcharper** [comment]
Try command shift G, or, try using the terminal.

**Comment by sunfish62** [comment]
OldBunny: A couple of points. You will probably want to familiarize yourself with the Terminal, as that is the most direct way to use/evaluate git. Next, your screenshot is only giving you a partial view of your system. OS X hides a lot of files and folders from normal view in Finder. To see where git is, and whether you've got it installed correctly, open a terminal window, and type:

which git

This will tell you the exact file that runs when you type "git" in the terminal. Mine shows:

DHT-Retina:Gnucash david$ which git
/usr/local/bin/git

Next, type:

git --version

This will tell you the version of git you have running. It should show:

DHT-Retina:~ david$ git --version
git version 2.5.0

If it shows 1.6.1 (which mine did), you will need to tinker around with the system to redirect git to your new download. Take a look at the information at:

http://sourceforge.net/projects/git-osx-installer/files/?source=navbar 

I will note that I had to alter the commands on my Yosemite installation, as the paths were slightly different than the ones there. My commands ended up being:

sudo mv /usr/local/bin/git /usr/bin/git-system
sudo ln -sf /usr/local/git/bin/git /usr/local/bin/git

Issuing those commands and restarting Terminal will get git going

**Comment by dan-ator** [comment]
@sunfish62 I tried using the sudo code you put in there in my command prompt but it asks for a password before it even lets me put in the second line.  Problem is when I type nothing is entered into the command prompt.  It seemingly will not let me enter a password.  Have you encountered this?

**Comment by OldBunny2800** [comment]
Happened to me too, just type in your password and press enter and everything will work.

**Comment by dan-ator** [comment]
For some reason it will not let me enter the password.  The terminal lets me enter in things and even type control-c to cancel the request of the sudo but nothing appears onscreen when I type the password, though when I hit enter it takes that as inputing something.

**Comment by sunfish62** [comment]
Dan, as oldbunny noted, the password does not display in the terminal screen. 

http://osxdaily.com/2015/02/04/terminal-wont-show-password-when-typed/

If you put in the wrong password, OS X responds with "Sorry, try again." Is that what you are seeing?

**Comment by dan-ator** [comment]
Ok now I understand.  Yup, it worked, now it displays version 2.5.0 when i
check it in the terminal.  Thanks!

On Thu, Sep 10, 2015 at 6:40 PM, sunfish62 <notifications@github.com> wrote:

> Dan, as oldbunny noted, the password does not display in the terminal
> screen.
>
> http://osxdaily.com/2015/02/04/terminal-wont-show-password-when-typed/
>
> If you put in the wrong password, OS X responds with "Sorry, try again."
> Is that what you are seeing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timcharper/git_osx_installer/issues/57#issuecomment-139402540>
> .
>



-- 
Daniel Alexander

**Comment by tobinorourke1298** [comment]
I have a similar issue in that I can't seem to open the git-2.6.4-intel-universal-mavericks.pkg on my MAC OS X v 10.6.8. when I type "git --version" into terminal it responds "illegal instruction". any guidance appreciated?

**Comment by timcharper** [comment]
@tobinorourke1298 you can't install the mavericks git installer for os x 10.6.8; there's an older release that will work for your version.

**Comment by tobinorourke1298** [comment]
thanks @timcharper! Appreciate the feedback. Any idea what version to download? There are many. Thanks in advance...

**Comment by timcharper** [comment]
git-2.3.5-intel-universal-snow-leopard.dmg
