### ISSUE TITLE
Downloading on OS Yosemite

### ISSUE THREAD

**Issue by DRose2** [timcharper/git_osx_installer#59]
Hi, I'm trying to download on my Mac with Yosemite OS, and nothing is opening up.  The screenshot below is what appears when I open from my "downloads" file.  I'm non technical, so not sure what the issue could be.  
![screen shot 2015-09-14 at 7 17 12 pm]
![screen shot 2015-09-14 at 7 17 12 pm](https://cloud.githubusercontent.com/assets/14286035/9866534/52cd9d74-5b18-11e5-9860-8d4b998e5ee5.png)

**Comment by timcharper** [comment]
You need to open the package, `git-2.5.0-intel-univeresal-mavericks.pkg`.
