### ISSUE TITLE
Recommendation for OS X El Capitan

### ISSUE THREAD

**Issue by smnirven** [timcharper/git_osx_installer#60]
Apple is adding a feature called System Integrity Protection in OS X El Capitan. This makes it impossible to modify anything in /usr/bin unless you reboot the machine in recovery mode & disable SIP. You can read more about SIP here:

http://arstechnica.com/civis/viewtopic.php?f=19&t=1285405
https://developer.apple.com/videos/wwdc/2015/?id=706

I'm wondering if there's a better way than disabling SIP?

**Comment by timcharper** [comment]
Good news, the installer doesn't modify /usr/bin!

**Comment by smnirven** [comment]
Right -- but the FAQ gives instructions for folks that have XCode installed that modify /usr/bin. That's what I was referring to.

**Comment by timcharper** [comment]
The latest installer has been updated and should work for El Cap. It installs symlinks in `/usr/local/bin`. El Capitan, by default, sets the `PATH` environment variable to prefer `/usr/local/bin` over `/usr/bin`, which makes any modifications to `/usr/bin` unnecessary.
