### ISSUE TITLE
OS X El Capitan

### ISSUE THREAD

**Issue by GitHubKen** [timcharper/git_osx_installer#63]
git-2.5.3-intel-universal-mavericks won't install on OS X El Capitan due to the following screen shot.

![screen shot 2015-10-04 at 9 20 53 am](https://cloud.githubusercontent.com/assets/9010454/10268021/7c209c60-6a79-11e5-8147-784c12465646.png)

**Comment by GuiVaccaro** [comment]
Hi, right click the install icon and choose Open. It will show an "Open" button in this screen. It shall work.

**Comment by dnewcombe** [comment]
Worked perfect for me!
