### ISSUE TITLE
What is the password for terminal

### ISSUE THREAD

**Issue by i-leonard** [timcharper/git_osx_installer#64]
in Step 2 of the Got OSx Installer instructions, it says to Remove stubs by calling "sudo mv /usr/bin/git /usr/bin/git-system" in terminal (I assumed).

Terminal then asks for a password and I'm not sure what that password is:

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:
Sorry, try again.
Password:

What am I supposed to type here? my computer admin login won't work

**Comment by timcharper** [comment]
If you are using El Cap, the latest installer will not require this step.

Otherwise, sudo should work with your account password. If that doesn't work, then you probably don't have admin access, or something that's outside of the scope of an installer issue.
