### ISSUE TITLE
git 1.6.0.... executables (leopard, 10.5.7 or less), any?

### ISSUE THREAD

**Issue by anongithub** [timcharper/git_osx_installer#76]
1.6.0.6 was the final Leopard version (Intel only I believe).  Is the code or its executable versions (preferred) for OS X 10.5.7 or less archived somewhere?  That is, can 1.6.0.6 executable be hosted/posted as well? 

Only reference for Leopard versions I found was in the rel. notes.  Even the build files for what is posted only start with snow leopard.  Indirectly, my inquiry could be interpreted as asking why git code/executables only goes back to snow leopard, but my true inquiry is actually: is 1.6.0.6 or earlier available in either exec. or code format for Intel and/or ppc platform for OSX 10.5.7 or earlier?  And, if not, anyone know any other reliable URL to obtain it?

**Comment by timcharper** [comment]
Sorry, it's not supported, and there's no installer available for it. You'll have to build from source on your own.
