### ISSUE TITLE
“git-2.10.1-intel-universal-mavericks.pkg” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by happyagony** [timcharper/git_osx_installer#80]
My MacBook OS is macOS sierra version 10.12 (16A323), after I downloaded the git-2.10.1-intel-universal-mavericks.dmg and clicked git-2.10.1-intel-universal-mavericks.pkg, below error message pop up:

“git-2.10.1-intel-universal-mavericks.pkg” can’t be opened because it is from an unidentified developer.

Your security preferences allow installation of only apps from the App Store and identified developers.

“git-2.10.1-intel-universal-mavericks.pkg” is on the disk image “git-2.10.1-intel-universal-mavericks.dmg”. Safari downloaded this disk image today at 17:22 from sourceforge.net.

**Comment by happyagony** [comment]
I can open it from system->security.

**Comment by Tabares** [comment]
I cannot install with the above solutions, I installed Xcode from the App store, this program has an apple git  version.

**Comment by prudvirazbanala** [comment]
Open system preferences ->security & privacy ->General tab ->click the select changes (downleft) -> select open anyway the github

**Comment by zamebit** [comment]
Thanks! 👍  it worked

**Comment by miosid3** [comment]
Thanks it worked for me too. the system preferences one.

**Comment by leemthompo** [comment]
Also —simply **ctrl+click** gives you the option to "open" which will then prompt you the option to open despite not being an official App Store app.

**Comment by yusfarhanchepa** [comment]
thanks!

**Comment by advchu** [comment]
Awesome Thanks Prudviraj

**Comment by lokesh993** [comment]
Thanks, It worked👍🏻✌🏻

**Comment by KshetriDeepen** [comment]
thankx prudviraj

**Comment by Youjam95** [comment]
> Open system preferences ->security & privacy ->General tab ->click the lock to make changes (downleft) -> select open anyway

thanks

**Comment by mohfurqon0210** [comment]
good, thanks for the solution

**Comment by waleedrashid** [comment]
Thanks @prudvirajprogrammingknowledge

**Comment by akummusic** [comment]
How do we uninstall it? I can't seem to run the uninstall.sh file

**Comment by vamsikrishnasabbisetty** [comment]
thanks @PrudviRajBanala . Should i close the lock after the installation goes through successfully ?
