### ISSUE TITLE
Total Newb - I've Downloaded, now what?

### ISSUE THREAD

**Issue by tricerabrand** [timcharper/git_osx_installer#90]
Hello everyone.  I suddenly feel very out of my league.  I downloaded git-osx-installer to my mac, then installed it, and now I'm staring that this and thinking "Now what?".  Never having written code before, this might be my first sign that I need some pre-requesities, but I dove in anyway.  Please help.
Thanks you!

![image](https://cloud.githubusercontent.com/assets/26487693/24761822/beb1941c-1aa9-11e7-8ffa-646f75123e6a.png)

**Comment by cserpell** [comment]
I think you should search into what git command line is, unless you are using it as a plugin for an IDE.
