### ISSUE TITLE
Having problem while downloading Git-2.13.1.2-64-bit.exe.

### ISSUE THREAD

**Issue by nvmanishkant** [timcharper/git_osx_installer#93]
I have downloaded Git-2.13.1.2-64-bit.exe couple of times but after downloading I could not able to install it. And now I am not able to download it completely, attaching the error :

![gitdownloadingerror](https://user-images.githubusercontent.com/29480796/27224029-b7b39b4e-52b0-11e7-8092-c36b273e990a.png)
![giterror](https://user-images.githubusercontent.com/29480796/27224030-b7b593cc-52b0-11e7-89b6-e975b3c90649.png)

**Comment by timcharper** [comment]
Hey there! This is the OSX installer :)
