### ISSUE TITLE
can't load Git after downloading

### ISSUE THREAD

**Issue by JGRobinson17** [timcharper/git_osx_installer#94]
Receive this message when I try to open the download: 

Safari can't resume the download

The file “git-2.7.1-intel-universal-mavericks.dmg-2.download” doesn’t appear to be a valid download file.

Any help would be great!

Thanks

**Comment by srikant** [comment]
Same issue, I have macOS Sierra
![screen shot 2017-09-16 at 12 19 27 am](https://user-images.githubusercontent.com/360666/30498544-c737a806-9a74-11e7-92e8-7ec841668c15.png)

**Comment by pinkchaintool** [comment]
Go to security/privacy to allow the application. Then go to your terminal and type git GUI to find the installation. If you are using mac go check this out https://www.youtube.com/watch?v=BqspebBGW9k

**Comment by olamieUsman** [comment]
After downloading the git. Right-click on the installer then click open. It extracts the installation package for you then right-click on the .dmg, click open and click open on the option given. Following the installation process, after installation, go to your terminal and type git gui to cotinue. Good luck!
