### ISSUE TITLE
CAN'T OPEN GIT AFTER INSTALLED

### ISSUE THREAD

**Issue by LBACCA94** [timcharper/git_osx_installer#95]
After I installed the package, when I try to open the GIT folder it appears me this message:

“git-2.7.1-intel-universal-mavericks.pkg” can't be open because it comes from a non identifies developer.

Any help will be great, thanks.

**Comment by ReneMoawad** [comment]
Go to System Preferences / Security and privacy / Allow apps downloaded from: App Store and identified developers

**Comment by Fridalin** [comment]
I can't find the software after installation.

**Comment by pinkchaintool** [comment]
<img width="712" alt="screen shot 2017-10-15 at 7 23 35 pm" src="https://user-images.githubusercontent.com/32003538/31590937-14014058-b1df-11e7-8f53-670c9d87dcc7.png">
I see this and then cannot find the software after it supposedly gets installed.

**Comment by pinkchaintool** [comment]
If you are using mac go to about 1:05 in this video https://www.youtube.com/watch?v=BqspebBGW9k
