### ISSUE TITLE
Can't find the software after insatlled

### ISSUE THREAD

**Issue by victorsheh** [timcharper/git_osx_installer#96]
I just download the package and installed it, but I couldn't find it.

**Comment by Fridalin** [comment]
Same issue here.

**Comment by pinkchaintool** [comment]
Same for me. If anyone finds out how the heck to make it work let me know!

**Comment by pinkchaintool** [comment]
If you are using mac go to about 1:05 in this video https://www.youtube.com/watch?v=BqspebBGW9k

**Comment by olamieUsman** [comment]
After the installation, open your terminal, type git gui then click enter.

OR else...
 go to the project you want to add git and start your usual command starting from git add .

Use git --version to see git version. 

I hope this helps
