### ISSUE TITLE
Like several others, the installation is nowhere to be found

### ISSUE THREAD

**Issue by pinkchaintool** [timcharper/git_osx_installer#97]
<img width="712" alt="screen shot 2017-10-15 at 7 23 35 pm" src="https://user-images.githubusercontent.com/32003538/31590954-58581344-b1df-11e7-99ea-b26bf681aa25.png">
I can't find this anywhere even though it supposedly was installed. Any help?

**Comment by olamieUsman** [comment]
After the installation, open your terminal, type git gui then click enter.

OR else...
 go to the project you want add git and start your usual command starting from git add .

I hope this helps

**Comment by arsenio1975** [comment]
thanks it helped
